# Supabase local config — proyecto remoto msgfcxnqujgvkxrzkbsw
project_id = "msgfcxnqujgvkxrzkbsw"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[functions.verify-captcha]
verify_jwt = false
