export const STYLES = {
  wrapper: (isMobile: boolean): React.CSSProperties => ({
    minHeight: '100vh',
    backgroundColor: isMobile ? '#ffffff' : '#f8f9fa',
    display: 'flex',
    alignItems: isMobile ? 'flex-start' : 'center',
    justifyContent: 'center',
  }),
  card: (isMobile: boolean): React.CSSProperties => ({
    backgroundColor: '#ffffff',
    borderRadius: isMobile ? '0' : '12px',
    padding: isMobile ? '24px 20px 88px' : '48px',
    width: '100%',
    maxWidth: isMobile ? '100%' : '560px',
    minHeight: isMobile ? '100vh' : 'auto',
    boxShadow: isMobile ? 'none' : '0 2px 12px rgba(0,0,0,0.08)',
  }),
  titulo: (isMobile: boolean): React.CSSProperties => ({
    fontSize: isMobile ? '22px' : '24px',
    fontWeight: 700,
    color: '#1F3864',
    margin: '0 0 8px',
  }),
  subtitulo: (): React.CSSProperties => ({
    fontSize: '15px',
    color: '#6b7280',
    margin: '0 0 28px',
  }),
  input: (isMobile: boolean): React.CSSProperties => ({
    width: '100%',
    height: isMobile ? '52px' : '44px',
    fontSize: isMobile ? '16px' : '14px',
    padding: '0 14px',
    border: '1.5px solid #DEE2E6',
    borderRadius: '8px',
    color: '#212529',
    boxSizing: 'border-box',
    outline: 'none',
  }),
  botonPrimario: (isMobile: boolean): React.CSSProperties => ({
    width: isMobile ? '100%' : 'auto',
    height: isMobile ? '52px' : '44px',
    fontSize: isMobile ? '16px' : '14px',
    fontWeight: 600,
    background: '#1F3864',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    padding: isMobile ? '0' : '0 28px',
  }),
  botonDeshabilitado: (): React.CSSProperties => ({
    opacity: 0.45,
    cursor: 'not-allowed',
  }),
  chip: (seleccionado: boolean): React.CSSProperties => ({
    padding: '10px 14px',
    minHeight: '44px',
    borderRadius: '20px',
    fontSize: '14px',
    border: `1.5px solid ${seleccionado ? '#1F3864' : '#DEE2E6'}`,
    background: seleccionado ? '#EEF2FF' : '#ffffff',
    color: seleccionado ? '#1F3864' : '#495057',
    cursor: 'pointer',
    fontWeight: seleccionado ? 600 : 400,
    display: 'flex',
    alignItems: 'center',
  }),
  error: (): React.CSSProperties => ({
    color: '#dc2626',
    fontSize: '13px',
    marginTop: '6px',
  }),
  ayuda: (): React.CSSProperties => ({
    fontSize: '12px',
    color: '#6b7280',
    marginTop: '4px',
  }),
  subrubrosContainer: (): React.CSSProperties => ({
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
    marginTop: '12px',
  }),
  badge: (): React.CSSProperties => ({
    backgroundColor: '#1F3864',
    color: '#ffffff',
    borderRadius: '12px',
    padding: '2px 8px',
    fontSize: '12px',
    fontWeight: 600,
  }),
  notaVerde: (): React.CSSProperties => ({
    color: '#40C057',
    fontSize: '14px',
    marginTop: '16px',
  }),
  textarea: (isMobile: boolean): React.CSSProperties => ({
    width: '100%',
    minHeight: isMobile ? '100px' : '80px',
    fontSize: isMobile ? '16px' : '14px',
    padding: '12px 14px',
    border: '1.5px solid #DEE2E6',
    borderRadius: '8px',
    color: '#212529',
    boxSizing: 'border-box',
    outline: 'none',
    resize: 'vertical' as const,
  }),
  botonFixedBottom: (): React.CSSProperties => ({
    position: 'fixed' as const,
    bottom: 0,
    left: 0,
    right: 0,
    padding: '16px 20px',
    backgroundColor: '#ffffff',
    boxShadow: '0 -2px 12px rgba(0,0,0,0.10)',
  }),
  botonVolver: (): React.CSSProperties => ({
    position: 'absolute' as const,
    top: '24px',
    left: '20px',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: '#1F3864',
    fontSize: '24px',
  }),
}
